
# **Assignment - 1 : Getting Started**

---

This assignment will get you familiarized with python libraries required for ***data science*** and ***machine learning***. You will have to complete the code snippets and run them. 

## **Note :**   Use only the methods and attributes of the ```numpy``` library. **Do not** hard-code them. Avoid loops as much as possible.

---
## Part - 1
 In this part, you will work with the library ```numpy```. 




Import ```numpy``` with an alias name ```np```. Initialize two arrays $a$, $b$ of size $3 \times 5$ with random values and print them. 

In [44]:
import numpy as np

a = np.random.random((3,5))
b = np.random.random((3,5))

print("a = ",a)
print("b = ",b)

a =  [[0.1920723  0.72566962 0.7849367  0.97209836 0.85097142]
 [0.54359433 0.08979087 0.48887324 0.92793635 0.7876182 ]
 [0.48509423 0.45527936 0.21798577 0.17721338 0.07362367]]
b =  [[0.89239319 0.64017662 0.14333232 0.41412692 0.04910892]
 [0.20937335 0.73070812 0.65112277 0.4789783  0.27478051]
 [0.65222313 0.95644951 0.43552056 0.07013251 0.05773149]]


Initialize and print two arrays $c$ and $d$ having the following properties:
*   $c$ is a row vector with all non-negative integer values less than 100
* $d$ is a square matrix of size 3 having all entries as 0.0

In [45]:
c = np.arange(0,100,1)
d = np.zeros((3,3))

print('c = ',c,'\nd = ',d)

c =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] 
d =  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


We have $e$ as following : ```e = [[1,2,3],[4,5,6],[7,8,9]]```. Change $e$ as a numpy array and print it.

In [48]:
e = [[1,2,3],[4,5,6],[7,8,9]]
e = np.array(e)
print(e, type(e))

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>


$f$ and $g$ are two square matrices of size 5 such that all the entries of $f$ are 1 and $g$ is an identity matrix. Initialize them and print them

In [49]:
f = np.ones((5,5))
g = np.eye(5)

print(f)
print(g)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Reshape $c$ into a $10 \times 10$ matrix and name it $h$. Now flatten $h$, call it $c^\prime$ and print **YES** when the shapes of $c$ and $c^\prime$ are same. Otherwise print **NO**.

In [50]:
h = c.reshape(10,10)
print(h)
c_prime = h.flatten()
print(c_prime.shape)

if(c.shape == c_prime.shape):
   print("YES")
else:
   print("NO")

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
(100,)
YES


Let $A$ denote a randomly initialized three dimensional matrix of shape (2,10,5). Transpose $A$, call it $A^\prime$, such that its shape is (5,2,10) and print it.

In [51]:
A = np.random.rand(2,10,5)
print(A.shape)

A = A.transpose(2,0,1)
print(A.shape)
print(A)

(2, 10, 5)
(5, 2, 10)
[[[8.28710188e-02 2.60345073e-01 8.64119669e-01 8.41419619e-01
   3.13819115e-01 7.98964319e-01 8.27862801e-01 8.33687884e-01
   8.48303897e-01 9.55668150e-02]
  [9.65293351e-01 8.40561085e-01 5.16784366e-01 7.40377963e-02
   6.85499183e-02 4.36357084e-01 6.18736583e-01 2.23322973e-01
   4.61548152e-01 6.94764977e-01]]

 [[9.59707187e-01 6.91977512e-01 2.90872446e-01 7.27152079e-01
   4.19582757e-01 9.71624297e-01 9.65228149e-01 8.72179508e-01
   3.14652999e-01 8.36912139e-01]
  [7.51027307e-01 4.54973059e-02 1.56262424e-01 4.78915452e-01
   7.64962823e-02 4.97782831e-01 1.57244658e-01 2.42978180e-01
   1.62520685e-01 3.90958016e-01]]

 [[5.40760836e-01 8.95570328e-01 7.41082406e-01 3.59107525e-01
   8.77212039e-01 3.67702983e-01 6.98809998e-01 9.21315918e-02
   2.79294597e-01 5.34734870e-01]
  [3.43093864e-01 5.56415411e-02 9.77952410e-01 6.22794804e-02
   5.38792658e-01 5.83311915e-01 2.75508475e-01 4.79507305e-01
   6.79501804e-01 4.62962030e-02]]

 [[8.3746243

You have a matrix $X$ of size (10,5) filled with random values. Print the following :
* Minimum value and index where it occured, for each column
* Maximum value and the index where it occured, for each column
* Minimum value and index where it occured, for each row
* Maximum value and index where it occured, for each row
* Minimum value and index where it occured, for the entire matrix
* Maximum value and index where it occured, for the entire matrix

In [52]:
np.random.seed(0)
X = np.random.rand(10,5)

col_min = np.min(X, 0)
col_min_ind = np.argmin(X,0)

col_max = np.max(X, 0)
col_max_ind = np.argmax(X,0)

row_min = np.min(X,1)
row_min_ind = np.argmin(X,1)

row_max = np.max(X,1)
row_max_ind = np.argmax(X,1)

mat_min = np.min(X)
mat_min_ind = np.argmin(X)

mat_max = np.max(X)
mat_max_ind = np.argmax(X)

print(X)
print("Minimum value for each column: ", col_min)
print("Minimum value index for each column: ", col_min_ind)
print("Maximum value for each column: ", col_max)
print("Maximum value index for each column: ", col_max_ind)
print("Minimum value for each row: ", row_min)
print("Minimum value index for each row: ", row_min_ind)
print("Maximum value for each row: ", row_max)
print("Maximum value index for each row: ", row_max_ind)
print("Minimum value for matrix: ", mat_min)
print("Minimum value index for matrix: ", mat_min_ind)
print("Maximum value for matrix: ", mat_max)
print("Maximum value index for matrix: ", mat_max_ind)

[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443]
 [0.63992102 0.14335329 0.94466892 0.52184832 0.41466194]
 [0.26455561 0.77423369 0.45615033 0.56843395 0.0187898 ]
 [0.6176355  0.61209572 0.616934   0.94374808 0.6818203 ]
 [0.3595079  0.43703195 0.6976312  0.06022547 0.66676672]
 [0.67063787 0.21038256 0.1289263  0.31542835 0.36371077]]
Minimum value for each column:  [0.0871293  0.0202184  0.1289263  0.06022547 0.0187898 ]
Minimum value index for each column:  [3 3 9 8 6]
Maximum value for each column:  [0.97861834 0.79915856 0.94466892 0.96366276 0.87001215]
Maximum value index for each column:  [4 4 5 1 3]
Minimum value for each row:  [0.4236548  0.38344152 0.07103606 0.0202184  0.11827443 0.14335329
 0.0187898  0.61209572 0.06022547 0.1289263 ]

Find and print the following for the matrix X: 
* Mean of each row and column
* Standard deviation of each row and column
* Mean of the entire matrix
* Standard deviation of entire matrix

In [53]:
row_mean = np.mean(X, 1)
col_mean = np.mean(X, 0)
row_sd = np.std(X, 1)
col_sd = np.std(X, 0)
mat_mean =  np.mean(X)
mat_sd = np.std(X)

print("Mean of each row: ", row_mean)
print("Standard deviation of each row: ", row_sd)
print("Mean of each column: ", col_mean)
print("Standard deviation of each col: ", col_sd)
print("Mean of the matrix: ", mat_mean)
print("Standard deviation of the matrix: ", mat_sd)

Mean of each row:  [0.56706085 0.66447172 0.57705944 0.51762729 0.62761197 0.5328907
 0.41643268 0.69444672 0.44423265 0.33781717]
Standard deviation of each row:  [0.09445299 0.23322986 0.29189733 0.38052993 0.30431633 0.26338419
 0.25841437 0.12727959 0.23169975 0.18537332]
Mean of each column:  [0.56044382 0.46781457 0.62009909 0.64025127 0.40121685]
Standard deviation of each col:  [0.24687647 0.25752158 0.22948615 0.28054144 0.26584905]
Mean of the matrix:  0.5379651182755409
Standard deviation of the matrix:  0.27226582292177587


Let $Y$ denote a square matrix of size 10 with random values. Print the following:
* Determinant
* Rank of the matrix
* Diagonal Elements
* Trace
* Eigen values
* Matrices obtained after Singular Value Decomposition
* Inverse if exists, otherwise Pseudo-Inverse
* Multiplication $Y$ with $X$
* Element-wise multiplication of $Y$ and its inverse(or pseudo-inverse)

In [59]:
np.random.seed(3)
Y = np.random.rand(10,10)

det_Y = np.linalg.det(Y)
rank_Y = np.linalg.matrix_rank(Y)
diag_Y = np.diag(Y)
trace_Y = np.trace(Y)
evalues_Y = np.linalg.eigvals(Y)
u, s, vh = np.linalg.svd(Y)
inv_Y = np.linalg.pinv(Y)
mult_XY = np.matmul(Y,X)
elem_mult_XY = np.dot(Y, inv_Y)

print(
    "Determinant: ", det_Y,
    "\n\nRank of the matrix: \n",rank_Y,
    "\n\nDiagonal Elements: \n",diag_Y,
    "\n\nTrace: \n", trace_Y,
    "\n\nEigen values: \n",evalues_Y,
    "\n\nMatrices obtained after Singular Value Decomposition: \n","U:\n", u,"S:\n", s,"V:\n", vh,
    "\n\nInverse if exists, otherwise Pseudo-Inverse: \n", inv_Y,
    "\n\nMultiplication of  Y  with  X: \n", mult_XY,
    "\n\nElement-wise multiplication of  Y  and its inverse(or pseudo-inverse): \n", np.array_str(elem_mult_XY, precision = 3, suppress_small=True)
)

Determinant:  -0.012807808169095483 

Rank of the matrix: 
 10 

Diagonal Elements: 
 [0.5507979  0.45683322 0.44045372 0.84575087 0.4576864  0.36217621
 0.06152893 0.19897603 0.92672568 0.19638058] 

Trace: 
 4.497309545724899 

Eigen values: 
 [ 4.797525  +0.j          0.72411408+0.52238181j  0.72411408-0.52238181j
 -0.48250062+0.55413671j -0.48250062-0.55413671j -0.6909002 +0.j
 -0.25905659+0.32357377j -0.25905659-0.32357377j  0.2127855 +0.08352477j
  0.2127855 -0.08352477j] 

Matrices obtained after Singular Value Decomposition: 
 U:
 [[-0.31776408 -0.02455508 -0.60644878 -0.17883359 -0.12672161  0.14873878
  -0.17823942 -0.52859453 -0.02295855 -0.38570883]
 [-0.26118514 -0.10864541 -0.24911354  0.26547359  0.52168399 -0.25773901
  -0.46995326  0.21752636 -0.39285046  0.16234491]
 [-0.31347907 -0.34483471 -0.25292297  0.1214296   0.1486964   0.33436315
   0.54080229  0.48017168  0.05660692 -0.20966421]
 [-0.35815379  0.59490017  0.30255161  0.15850614 -0.11046295  0.3051409
   0.07

## End of Part - 1
 --- --- ---

## Part - 2
---
In this part, you will be working with the library ```pandas```. Import this library with an alias name ```pd```.

In [0]:
# Initial imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv
Read the data and display the first 5 rows

In [62]:
#Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv

file_url = "http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv"
data = pd.read_csv(file_url)
data.head(5)

pclass  survived  ...   body                        home.dest
0       1         1  ...    NaN                     St Louis, MO
1       1         1  ...    NaN  Montreal, PQ / Chesterville, ON
2       1         0  ...    NaN  Montreal, PQ / Chesterville, ON
3       1         0  ...  135.0  Montreal, PQ / Chesterville, ON
4       1         0  ...    NaN  Montreal, PQ / Chesterville, ON

[5 rows x 14 columns]

### Preprocessing of the Dataset



---


**1. Convert the categorical values of columns 'sex', 'embarked', 'pclass' into dummy values and add them into titanic_data_new DataFrame**




---





---


**2. Fill the missing data in Age and Fare columns with the mean value of the respected column then add these columns to titanic_data_new**


---



###Normalization


---



1. Normalize the columns which have numerical data



---





---
2. Drop the original age, fare columns
3. Append the normalized columns to the titanic_data_new DataFrame.



---



###Plotting
1. plot the age against the ID(continuous)
2. plot the fare against the ID(scatter)

## End of Part - 2
---

## Part - 3
---

In this part, you will work with the library ```matplotlib```. Import the ```pyplot``` from ```matplotlib``` with an alias name ```plt```.

In [0]:
import matplotlib.pyplot as plt

Plot the sine function with domain in $[-3\pi,3\pi]$. Label the axes appropriately. Add title $\sin(x)$. Use latex formatting while adding the title. Set the plot size to (10,10)

Plot $\sin(x)$ and its spectrum, $\cos(x)$ and its spectrum in a single plot, in the domain $[-2\pi,2\pi]$. Label the plot appropriately.

## End of Part - 3
---

Create a Github repository with the name ***SHALA2020*** and save this assignment there.